name: Basic Workflow

on:
  push:
    branches:
      - feature/basic-workflow

jobs:
  do-things:
    name: Do Things
    runs-on: ubuntu-latest
    steps:
      - name: La cosa que he hecho
        run: echo "¡He hecho una cosa!"

      - name: Un error que cometí
        run: |
          echo "¡He cometido un error!"
          exit 1
